import { genTitle } from "@/utils";
import "@/styles/index.css";

export const metadata = {
    title: genTitle("Home"),
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body>{children}</body>
        </html>
    );
}
