import { genTitle } from "@/contants";
import "@/styles/index.css";
import Header from "@/components/Header";
import { Poppins } from "next/font/google";

const poppins = Poppins({
    subsets: ["latin"],
    display: "swap",
    weight: "500",
    preload: true,
});

export const metadata = {
    title: genTitle("Home"),
    description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
    return (
        <section className={`${poppins.className}`}>
            <Header />
            {children}
        </section>
    );
}
